version: "3"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    ports: 
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
    env_file:
      - .env
    volumes:
      - ./db/data:/var/opt/mssql/data
      - ./db/log:/var/opt/mssql/log
      - ./db/secrets:/var/opt/mssql/sec
